---
env:
  browser: true
  es6: true
extends:
  - airbnb-base
parserOptions:
  sourceType: module
  ecmaVersion: 6
rules:
  import/extensions: 0
  import/prefer-default-export: 0
  prefer-destructuring: 0
